apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anomaly-scoring-api.fullname" . }}-config
  labels:
    {{- include "anomaly-scoring-api.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ default "" $v | quote }}
  {{- end }}
