apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-learning-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: REPLACE_ME_REPO_URL
    targetRevision: HEAD
    path: argocd/applications
    directory:
      recurse: false
      include: '{recommendation-api.yaml,cluster-addons.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
